/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChatClient;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import javax.swing.SwingConstants;

/**
 *
 * @author ZISHAN
 */
public class GroupChat extends javax.swing.JFrame {
     Client client;
     ArrayList<JLabel> onlineList;    /**
     * Creates new form 
     * @param client
     */
    public GroupChat(Client client) {
        initComponents();
        jScrollPane1.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
        this.client=client;
        onlineList=new ArrayList<JLabel>();
        new Thread(new ReadMsg(client,msgBox,onlineUser,onlineList)).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatBox = new javax.swing.JTextField();
        onlineUser = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnViewProfile6 = new javax.swing.JButton();
        uploadImage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.lightGray);

        chatBox.setBackground(new java.awt.Color(255, 153, 0));
        chatBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatBoxActionPerformed(evt);
            }
        });
        chatBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chatBoxKeyPressed(evt);
            }
        });

        onlineUser.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout onlineUserLayout = new javax.swing.GroupLayout(onlineUser);
        onlineUser.setLayout(onlineUserLayout);
        onlineUserLayout.setHorizontalGroup(
            onlineUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        onlineUserLayout.setVerticalGroup(
            onlineUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel25.setBackground(new java.awt.Color(255, 0, 0));
        jLabel25.setForeground(new java.awt.Color(102, 255, 102));
        jLabel25.setText("IMAGE");

        jLabel26.setBackground(new java.awt.Color(153, 255, 102));
        jLabel26.setText("jLabel8");

        jLabel27.setText("jLabel9");

        btnViewProfile6.setText("VIEW COMPLETE PROFILE");

        uploadImage.setText("upload Image");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnViewProfile6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uploadImage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewProfile6)
                    .addComponent(uploadImage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        msgBox.setColumns(20);
        msgBox.setRows(5);
        jScrollPane1.setViewportView(msgBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(chatBox))
                .addGap(0, 0, 0)
                .addComponent(onlineUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(chatBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(onlineUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chatBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatBoxActionPerformed

    private void chatBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chatBoxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            sendMsg(chatBox.getText());
            chatBox.setText(null);
        }
    }//GEN-LAST:event_chatBoxKeyPressed

    /**
     * @param args the command line arguments
     */
 void sendMsg(String msg){
         try {
             client.write(msg);
         } catch (IOException ex) {
             Logger.getLogger(GroupChat.class.getName()).log(Level.SEVERE, null, ex);
         }
 }
class ReadMsg implements Runnable{
        Client client;
        JTextArea msgBox;
        JPanel onlineUser;
        ArrayList<JLabel> onlineList;
        public ReadMsg(Client client , JTextArea msgBox , JPanel onlineUser,ArrayList<JLabel> onlineList){
            this.client = client;
            this.msgBox = msgBox;
            this.onlineUser = onlineUser;
            this.onlineList=onlineList;
        }
        @Override
        public void run() {
            try{
                while(true){
                    String msg = client.read();
                    if(msg.startsWith("USERLIST: ")){
                        //System.out.println("Hello");
                        String users[] = msg.split(" ")[1].split(",");
                      /*  for(int i=0;i<users.length;i++)
                            System.out.println(users[i]);*/
                        onlineList.clear();
                        onlineUser.removeAll();
                        onlineUser.revalidate();
                        onlineUser.repaint();
                        for(int i = 0 ; i < users.length;i++ ){
                            JLabel online=new JLabel(users[i],SwingConstants.CENTER);
                            if(!users[i].equals(client.getUserName()))
                            onlineList.add(online);
                        }
                        for(int i = 0 ; i < onlineList.size();i++){
                            onlineList.get(i).setForeground(Color.blue);
                            onlineList.get(i).setVisible(true);
                            onlineList.get(i).setBounds(5,5+(i-1)*20,150,20);
                            onlineUser.add(onlineList.get(i));
                                }
                        for(int i=0;i<onlineList.size();i++){
                            onlineList.get(i).addMouseListener(new java.awt.event.MouseAdapter(){
                                public void mouseClicked(java.awt.event.MouseEvent evt){
                                    System.out.println("prem");
                                }
                            });
                            
                        }
                    }
                    else if(msg.startsWith("ChatServer: "))
                            {
                        
                    }
                    else{
                        String oldMsg = msgBox.getText();
                        msgBox.setText( oldMsg+"\n"+msg);
                    }
                }
            }catch(Exception ex){
                System.out.println(ex);
            }
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewProfile6;
    private javax.swing.JTextField chatBox;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea msgBox;
    private javax.swing.JPanel onlineUser;
    private javax.swing.JButton uploadImage;
    // End of variables declaration//GEN-END:variables
}
